### ISSUE TITLE
Not useful for newer versions

### ISSUE THREAD

**Issue by pfjarschel** [charlielito/install-dlib-python-windows#2]
Unfortunately, there are no whl files for the newer versions.

**Comment by Davidnet** [comment]
I encounter the same error

**Comment by p0123n** [comment]
It works for me:
https://stackoverflow.com/questions/41912372/dlib-installation-on-windows-10

```
pip install https://pypi.python.org/packages/da/06/bd3e241c4eb0a662914b3b4875fc52dd176a9db0d4a2c915ac2ad8800e9e/dlib-19.7.0-cp36-cp36m-win_amd64.whl#md5=b7330a5b2d46420343fbed5df69e6a3f
```

**Comment by charlielito** [comment]
Actually, in the link provided in Readme (https://pypi.org/simple/dlib/) you can find wheels up to 19.8 for windows. There are also .tar up to 19.17 versions that you could download and follow instructions to install it.
