### ISSUE TITLE
ERROR: dlib-19.7.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by archmord** [charlielito/install-dlib-python-windows#3]
I'm getting an error for windows 10
Any idea how to fix it

**Comment by charlielito** [comment]
Can you provide us more info? Your system is x64?

**Comment by archmord** [comment]
AMD cpu 64bit

**Comment by imneonizer** [comment]
Same problem on intel i7 x64

**Comment by BonnieMuthaka** [comment]
Same problem here. On x64 Intel i3. CMake already installed, Python 3.7 is already in good shape.

**Comment by adhikarimilan** [comment]
Sane problem on x64 Intel I3

**Comment by shristi428** [comment]
maybe the problem with the version of python . use python 3.5 or 3.6

**Comment by ngquoccuong** [comment]
same problem with python 3.8, pip 20.2 on windows 10, x64 intel i5.

**Comment by chandreshmunjapara** [comment]
i am using pythone 3.8.6 and64 bit i am getting same error

**Comment by charlielito** [comment]
Yes, the issue is trying to use a `.whl` file targeted for a specific version of python (in this case for version `3.6`) with a different one. You cannot use python 3.8 or python 3.7. For this to work you MUST use python3.6 or look for a `.whl` compatible with the version you want to use.

**Comment by LakshitaJoshi** [comment]
same problem amd cpu 3.10 python version error .whl not supported. pls suggest some methods to solve. neither it is installing for pycharm nor for jupyter nb
